### ISSUE TITLE
Updates to ISARIC variables: add clinical characteristics

### ISSUE THREAD

**Issue by wjchulme** [opensafely-core/databuilder#1071]
In support of the ISARIC validation project, the following variables in the `isaric_raw` table need to be added to the tpp backend:

`chrincard`
`hypertension_mhyn`
`chronicpul_mhyn`
`asthma_mhyn`
`renal_mhyn`
`modliv`
`mildliver`
`chronicneu_mhyn`
`malignantneo_mhyn`
`chronichaemo_mhyn`
`aidshiv_mhyn`
`obesity_mhyn`
`diabetescom_mhyn`
`diabetes_mhyn`
`rheumatologic_mhyn`
`dementia_mhyn`
`malnutrition_mhyn`
`diabetes_type_mhyn` (taking values `"No", "1", "2", "N/K"`)
`smoking_mhyn` (taking values `"Yes", "Never Smoked", "Former Smoker", "N/K"`)

~All but the last two variables take values `"YES", "NO", "Unknown"`. Null values will occur if `comborb_none!=""` (indicating no comorbidities) according to the data dictionary. This implies null values are semantically equivalent to `"No"`. Information wise, these variables are essentially nullable booleans, but I think it's preferable to retain the string values due to issues with nulls for booleans in pandas. So:~

~`"Yes"` -> `"Yes"`~
~`"No", NULL"` -> `"No"`~
~`"Unknown"` -> `"Unknown"`~

~But I need to confirm whether that's an approrpriate interpretation of nulls.~

UPDATE:

All but the last two variables take values `"YES", "NO", "Unknown", "NA"`. `"NA"` values occur if `comborb_none=="No comorbidities"`. This implies null values are semantically equivalent to `"No"`. So:

`"YES"` -> `"Yes"`
`"NO", "NA"` -> `"No"`
`"Unknown"` -> `"Unknown"`

`diabetes_type_mhyn` and `smoking_mhyn` also currently return values as is. There may be an advantage to standardising "unknown"/"N/K"/"Don't know" type values across the dataset, but it would be good to get input from others about this.

**Comment by StevenMaude** [comment]
@wjchulme:

> due to issues with nulls for booleans in pandas

I've not used pandas for a while, but does the [nullable Boolean type](https://pandas.pydata.org/docs/user_guide/boolean.html) that pandas offers now (from 1.0) help here? Or is that part of the problem you're alluding to?

**Comment by StevenMaude** [comment]
The TPP `patients` table currently uses ["unknown" as a value](https://github.com/opensafely-core/databuilder/blob/21c0c95d3dbf728e32d87ddfaf741648794df9a6/databuilder/backends/tpp.py#L23); I'm not sure if was decided by any process, or just arbitrarily chosen.

**Comment by evansd** [comment]
> I think it's preferable to retain the string values due to issues with nulls for booleans in pandas

I'd rather not let the idiosyncrasies of Pandas drive our data modelling, if possible. ehrQL makes it pretty easy to transform values if you need to make them more Pandas friendly. If it's just a case of treating NULL like False then you can do:
```py
nullable_boolean_series.if_null_then(False)
```

Or if you really want strings then:
```py
nullable_boolean_series.map_values({False: "No", True: "Yes"}).if_null_then("You tell me")
```

---

> The TPP `patients` table currently uses ["unknown" as a value](https://github.com/opensafely-core/databuilder/blob/21c0c95d3dbf728e32d87ddfaf741648794df9a6/databuilder/backends/tpp.py#L23); I'm not sure if was decided by any process, or just arbitrarily chosen.

I think that CASE statement is slightly misleading because `sex` is never actually NULL, it's one of `M`, `F`, `I`, `U`; so `unknown` is just reflecting the meaning of `U`.

---

Side note: would it makes sense to remove those `_mhyn` suffixes from the column names while we're doing this work? I think part of the work in ehrQL-ising a table involves bringing its names inline with some kind of (as yet unspecified) ehrQL "house style". And those suffixes don't seem to quite fit to me.

**Comment by wjchulme** [comment]
Thanks, Dave, good to know about nulls in ehrQL. In that case having:

`"Yes"` -> `True`
`"No", "NULL"` -> `False`
`"Unknown"` -> `NULL`

is one possibility (pending confirmation of what NULL means for these variables in isaric -- I intend to check today). 

But this breaks a rule about structural nulls (for want of a better term), in the sense that we only should use null values to mean "this question doesn't make sense in this patient". For example, we'd represent cause of death as `null` for someone who is alive, and use `"Unknown"` for someone who is dead but we don't know what killed them. 

Whether we want to conform to this rule in another matter. I'm keen to hear you thoughts.

**Comment by wjchulme** [comment]
Open to removing the `_mhyn` suffixes as long as there's clear documentation about how these names are transformed. A user looking at the tpp schema notebook, or the isaric data dictionary, would need to know that the variables names there are not those used to access the variables in data builder.

**Comment by evansd** [comment]
Thanks, Will. That's a good point about structural nulls, which I hadn't considered. I don't think I have an immediate opinion on that. Certainly if we decide it's better modelling to have an explicit "unknown" value then I'd be very happy to do that. Just so long as the modelling isn't being driven by Pandas!

On the column names, if it's important to match up with external docs then that's fine. I just wanted to make sure we'd considered the option to rename rather than blindly copying across. For what it's worth, my assumption was that we would pull as much external documentation as possible into the schema definition where it automatically becomes part of the OpenSAFELY docs but I guess that's not always going to be practical.

As for the schema notebook, I'm hoping that eventually becomes a thing that only Bennett Institute staff ever need to look at. Ideally, everything in the TPP database gets exposed as an ehrQL table and everything you might want to know about those tables is included in the docs.

**Comment by StevenMaude** [comment]
Just to add some feedback on the column naming, based on having had to look at them a little:

* It is helpful to have the same names as the original columns:
  * either if people are familiar with the ISARIC data already
  * or if we're going back to TPP and referring to specific columns; there's no extra thinking step needed to go back and forth from the relevant variable name in ISARIC and the renamed variable in Data Builder
* However, if you're unfamiliar with the names, some of the names[^1] are:
  * fairly tricky to decipher without the data dictionary
    * *example*: `dsstdtc` is "Outcome date"
  * have what seem like inconsistent quirks
    * *example*: `corona_ieorres` versus `coriona_ieorres2` and `coriona_ieorres3` — note the additional `i` in the latter two names; I'm unsure if this has significance or is just a typo that's stuck
  * can be confused with variables of different types entirely, particularly if you were auto-completing or similar
    * *example*: `covid19_vaccine` is a nullable Boolean-type thing, while `covid_19_vaccined` is a date — these two I mixed up yesterday, which took me a while to understand

Perhaps those problems are not too bad, if you have a variable reference to use.

[^1]: My sympathies are with whoever did the naming, because the version of the data dictionary I have is 98 pages long and does have 800+ variables in it.

**Comment by wjchulme** [comment]
Yes, good points. I think that renaming is the right thing to do. I'll come back later with some suggestions. 

(Not keen on `date_of_first_covid_vaccine` over, say, `covid_vaccine_1_date` because it's quite long and `1,2,3..` is neater than `first, second, third`. But we can argue about that with the full list of suggestions.

**Comment by wjchulme** [comment]
>  Ideally, everything in the TPP database gets exposed as an ehrQL table and everything you might want to know about those tables is included in the docs

great!

**Comment by StevenMaude** [comment]
@wjchulme:

> The only other thing is that we just need to be careful about what precedent(s) we might be setting here with regard renaming conventions, retyping conventions, etc. Decisions made now may be difficult to undo.

Until we have a proper Data Builder v1 release, I don't believe there are any guarantees of backwards compatibility for dataset definitions. I've certainly had to update examples I've written before. So I don't think that any decision made now is absolutely fixed. Particularly as we may continue to add, remove columns, or change the column types for this table in future.

In this case, you are the only current user of the table. So, I'm inclined to say it's probably fine if we need to change the corresponding Data Builder table a few times.
 
@evansd may have other opinions though.

***

I think what this specific task suggests is that there's probably a related task, maybe worth opening an issue for, of defining and documenting the guidelines or standards we have for handling variable names and values from data sources.

**Comment by wjchulme** [comment]
I've updated the OP having checked relationship between the `comorb_none` variable and other comorbity variables. Essentially, `"NA"` mean "No".

**Comment by evansd** [comment]
> In this case, you are the only current user of the table. So, I'm inclined to say it's probably fine if we need to change the corresponding Data Builder table a few times.
> 
> @evansd may have other opinions though.

No, I agree with all of this. The other thing to bear in mind is that Data Builder allows us to have multiple different "views" on to the same table, so if we come up with a better API later we can introduce that under a different namespace without breaking existing code.

**Comment by StevenMaude** [comment]
@wjchulme:

I'm nearly done with this, I think. One point that would be helpful to clarify for me:

> All but the last two variables take values "YES", "NO", "Unknown", "NA". "NA" values occur if comborb_none=="No comorbidities". This implies null values are semantically equivalent to "No". So:
>
> "YES" -> "Yes"
> "NO", "NA" -> "No"
> "Unknown" -> "Unknown"

When you say:

> This implies null values are semantically equivalent to "No".

should a `null` (if present) also be mapped to `No` then, or just left alone?

**Comment by StevenMaude** [comment]
Another quick question:

> diabetes_type_mhyn (taking values "No", "1", "2", "N/K")
> smoking_mhyn (taking values "Yes", "Never Smoked", "Former Smoker", "N/K")

Are the `Yes`/`No` values in standard letter case? As compared with the all uppercase `YES/NO` values in other columns?

**Comment by wjchulme** [comment]
Regarding `null`s  -- sorry for the confusion. Yes, I removed mention of nulls because they don't exist for these variables. The value set is `["YES", "NO", "Unknown", "NA"]`.  If `null`'s were present, I think best left alone.

**Comment by wjchulme** [comment]
Confirmed values, with correct case:

`diabetes_type_mhyn`: `["NO", "1", "2", "N/K", "NA"]`
`smoking_mhyn `: `["Never Smoked", "Former Smoker", "Yes", "N/K", "NA"]`

No `null`s.
