### ISSUE TITLE
Replace `take` / `drop` and `set_population`

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/databuilder#1119]
There are some changes we'd like to make to ehrQL:

* replacing `take` / `drop` with `where` / `except_where`.  (see [this Slack thread](https://bennettoxford.slack.com/archives/C63UXGB8E/p1677685831079049?thread_ts=1675943293.499219&cid=C63UXGB8E))
* replacing `set_population` with `define_population` (see #843)

The work involves:

- [ ] changing the implementation and modifying [existing studies](https://docs.google.com/spreadsheets/d/1-lw0qZSRdZwPY2HrQh_wDkifvJKvtqR6WKie_WLQNJI/edit#gid=0) to use the new syntax (see @evansd's notes below on **Making a deprecation**)
- [ ] updating documentation as necessary

**Comment by evansd** [comment]
## Should we make a breaking change?

> Since there are only a few studies using ehrQL, these changes do not need backward-compatibility shims.

I'm actually not sure about this bit. It's true there are only a few studies. But despite the fact that, nominally, we are supposed to be writing all the ehrQL during this phase of development the dataset definitions are actually being worked on by external users. And even the fairly minor codelists change has caused [some confusion](https://bennettoxford.slack.com/archives/C04DVD1UQC9/p1678107263687809). Added to this, it's really easy to provide backwards compatibility in this case as it just involves defining three aliases for the renamed methods e.g.
```py
def take(self, series):  # pragma: no cover
    warnings.warn('Use `where` instead of `take`', DeprecationWarning, stacklevel=2)
    return self.where(series)
```

Our first users of ehrQL have been pre-warned of disruption and change, but I think it's still worth a bit of effort to make the process smoother for them.


## How to make a breaking change

Leaving aside the above, if we _do_ want to make changes to ehrQL that will break our [external acceptance tests](https://github.com/opensafely-core/databuilder/blob/b7ddf98373dcd76ed892c2e3ff0ec2bd8c1c1e51/tests/acceptance/test_external_studies.py#L25-L112) then the workflow looks like this:

 1. Create a Data Builder PR:
    - Make the relevant changes to ehrQL.
    - Run `pytest tests/acceptance/test_external_studies.py` and observe that the tests fail.
    - Fix our copies of the study code in `tests/acceptance/external_studies`.
    - Confirm that the tests now pass.
    - Create PR, get reviewed and merge as normal.
   
 2. Create PRs against individual study repos:
    - You can find the relevant repos and branches in the [external test config](https://github.com/opensafely-core/databuilder/blob/b7ddf98373dcd76ed892c2e3ff0ec2bd8c1c1e51/tests/acceptance/test_external_studies.py#L25-L112).
    - Clone them and checkout a new branch based on the appropriate target branch.
    - Copy the contents of each directory in `tests/acceptance/external_studies` into the relevant repo checkout.
    - Commit, push and open a PR.
    - Contact the relevant users on Slack and explain what the PR is for (we can't rely on everyone seeing the Github notification).

In the meantime, the [`update-external-studies`](https://github.com/opensafely-core/databuilder/blob/b7ddf98373dcd76ed892c2e3ff0ec2bd8c1c1e51/.github/workflows/update-external-studies.yml) workflow will spot that our code no longer matches what's in the external repos and will create a PR to undo our changes. This PR will fail tests and so it can't be inadvertently merged. Once all the study PRs created above have been merged the workflow will detect that there are no changes to make and will automatically close the PR.

**Comment by rebkwok** [comment]
@evansd Just a comment for any future similar things really.

This isn't quite enough to test the studies:
```
find . -name 'dataset_def*.py' | xargs -n 1 python
```

A few have helper modules like a `variables_lib.py` which have functions used by the dataset definition.  One has a `datasets.py` which is used to build the dataset definition files.  The QOF study has a `dm_dataset.py` which contains a helper function to create the `Dataset()`s.   Because all the ehrQL is in functions in the helper modules, calling them with `python variables_lib.py` etc doesn't pick up on the deprecated ehrQL.  I've been also grepping all the  files in the `analysis/` folders, and then running `opensafely run run_all` on each study to check they pass (or at least, fail in the same way as the current study branch does).

Although, I've just realised that the deprecation warnings don't appear in either the console output or the logs, so running the OS CLI isn't actually that helpful.

**Comment by evansd** [comment]
Thanks @rebkwok. I don't quite understand the problem here though. All Data Builder itself does is import the dataset definition module to retrieve the value of `dataset`. It's true that just importing, say, `variables_lib` won't necessarily catch issues in that file. But importing the dataset definition which _uses_ `variables_lib` will catch the issues. Won't it? Or am I missing something.

I guess the exception to this will be parameterised definitions where the arguments passed to the dataset definition change the ehrQL that's run. I suppose we'd have to parse the arguments out of the `project.yaml` or something nasty like that if we wanted to fully test those. But I think we've only got one example of that being worked on at the moment.


> Although, I've just realised that the deprecation warnings don't appear in either the console output or the logs

You're quite right. How annoying! They do appear if you run `python analysis/dataset_definition.py` so I naively assumed they'd appear from within Data Builder too. Hopefully there's an easy fix there.

**Comment by evansd** [comment]
Here's the answer:
https://docs.python.org/3/library/exceptions.html#DeprecationWarning
> Ignored by the default warning filters, except in the `__main__` module

So it shows by default when executing the module directly, but not when it's imported.

**Comment by rebkwok** [comment]
> But importing the dataset definition which uses variables_lib will catch the issues. Won't it? 

No, it doesn't.  
For example, this [dataset definition ](https://github.com/opensafely/cis-pop-validation-ehrql/blob/4470649b4d11e98d23c9d3bb8819e2ef4a5d5fe2/analysis/dataset_definition.py#L16) in the ONS CIS validation study import and uses `has_matching_event` (among others) from `variable_lib.py`.  

Running `find . -name 'dataset_def*.py' | xargs -n 1 python` shows lots of warnings, so I replace all the deprecated ehrQL methods in the `dataset_definition.py` file and run it again, and I get no warnings.  However, `has_matching_event` in `variable_lib.py` still has the deprecated methods in it.

**Comment by evansd** [comment]
Ahhh, yes I understand! You're talking specifically about DeprecationWarnings. And yes, I've just discovered that by default they're only shown if they occur in the `__main__` module, which I wasn't expecting.

Last time I did this I ended up testing the dataset definitions against a version of Data Builder with the backwards compatibility stuff removed. That made the issues errors rather than warnings so there was no chance of them passing silently.

This is my fault for making assumptions about default warning behaviour based on the fact that I saw _some_ warnings when I ran a dataset definition.

You can get the behaviour I _thought_ was the default by setting an env var:
```
PYTHONWARNINGS='default::DeprecationWarning' python ...
```

**Comment by rebkwok** [comment]
Hmm, nope.  That still doesn't show warnings for deprecated methods in `variable_lib.py`.  I also tried using [python development mode](https://docs.python.org/3/library/devmode.html#devmode) as suggested in https://docs.python.org/3/library/exceptions.html#DeprecationWarning

**Comment by rebkwok** [comment]
I think removing the deprecated methods and running `find . -name 'dataset_def*.py' | xargs -n 1 python` to check for errors is the best way to go

**Comment by evansd** [comment]
Making them errors is the sure-fire way to do it. That's weird it's not working for you though. If I run this:
```
cd cis-pop-validation-ehrql
PYTHONWARNINGS='default::DeprecationWarning' python analysis/dataset_definition.py
```

I get this:
```
/home/dave/projects/ebmdatalab/ehrql-studies/cis-pop-validation-ehrql/analysis/dataset_definition.py:40: DeprecationWarning: Use `where` instead of `take`
  primary_care_covid_events = clinical_events.take(
/home/dave/projects/ebmdatalab/ehrql-studies/cis-pop-validation-ehrql/analysis/variable_lib.py:35: DeprecationWarning: Use `where` instead of `take`
  active = addr.take(
/home/dave/projects/ebmdatalab/ehrql-studies/cis-pop-validation-ehrql/analysis/dataset_definition.py:61: DeprecationWarning: Use `where` instead of `take`
  prior_events = clinical_events.take(clinical_events.date.is_on_or_before(index_date))
...
```

Which includes a warning from `variable_lib.py` on the second line.
