### ISSUE TITLE
`practice_registrations.start_date` and `.end_date` should be date not datetime

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/databuilder#1183]
The `practice_registrations` ehrQL table has `start_date` and `end_date` columns, which are defined as `Series(datetime.date)`

https://github.com/opensafely-core/databuilder/blob/632bb89380788f57d2b8450b7acbf60b997f9ffd/databuilder/tables/beta/tpp.py#L35-L38

However, the backend doesn't cast these columns to `date`

https://github.com/opensafely-core/databuilder/blob/632bb89380788f57d2b8450b7acbf60b997f9ffd/databuilder/backends/tpp.py#L49C10-L54

and these columns are `datetime` in [the corresponding the database table](https://reports.opensafely.org/reports/opensafely-tpp-database-schema/#RegistrationHistory).

**Comment by evansd** [comment]
Ouch! This is not good and I'm very glad you spotted this so early on.

The real issue here is that our test schema has them coded as `date` (because it was copied from Cohort Extractor):
https://github.com/opensafely-core/databuilder/blob/632bb89380788f57d2b8450b7acbf60b997f9ffd/tests/lib/tpp_schema.py#L291-L292

If the type was correct there then the tests would have caught this immediately.

To me, this is more evidence that we really need the feature described here sooner rather than later:
 * https://github.com/opensafely-core/databuilder/issues/1104
