### ISSUE TITLE
Implicit sort on primary key to ensure stability and consistency of results

### ISSUE THREAD

**Issue by benbc** [opensafely-core/databuilder#461]
When we sort event-dimensioned tables on a column that has identical values, the resulting order is undefined. This can give undetermined values for variables where we pick a column that has different values in two records with identical values for the sort column.

For example, this query

```
e.sort_by(e.i).first_for_patient().b
```

with this data

```
          |  i  | b
        --+-----+---
        1 | 101 | T
        1 | 102 | F 
        2 | 200 | T 
        2 | 200 | F 
```

will always give `True` for patient `1`, but can return either `True` or `False` for patient `2`.

This behaviour has two unsatisfactory consequences:

1. Researchers may see different results when re-running their queries. (This is probably a theoretical problem only because of the scale of real data, but may cause problems when testing with small synthetic datasets.)
2. In our tests we'll see different results for different engines which causes problems for our generative tests.

The proposed solution is that we an an implicit sort by primary key to resolve ties consistently.

This means that we have to insist that all event-dimensioned tables have a primary key. We could potentially allow for a composite "natural" key so that this is less of a constraint on backend implementers.

Note: sorting is disabled in the generative tests to avoid this problem; it should be re-enabled as part fixing this.

**Comment by evansd** [comment]
> This is probably a theoretical problem only because of the scale of real data, but may cause problems when testing with small synthetic datasets.)

I think it's theoretical in the sense that it's unlikely to ever cause a meaningful difference in a study outcome. But it's definitely caused real world confusion in the past when researchers extracted what should have been the same population twice and got very slightly different results.

In my head, this was a problem that had to be solved by ehrQL authors (and generally by reusable variable authors, rather than individual study authors) so I wasn't really thinking about it from the query engine perspective. But now it's been highlighted, and we have what looks like a reasonable solution, it seems obvious that we should try to address this within the query engines.

**Comment by evansd** [comment]
I was thinking about this would interact with "YOLO" mode where we don't know the schema in advance. But I think it all works out OK. We already have [good reason](https://github.com/opensafely-core/databuilder/blob/324933e6c5a203058fbbca2d4b5660fc007b5a6f/databuilder/query_engines/sqlite.py#L229-L234) to want to determine, at the point where we're applying a sort-and-pick, which columns we're going to want to select from the resulting frame.

Our behaviour can then be to sort by any of these columns which aren't already sorted on. This might not itself be enough to make the order fully determined. But necessarily it will be fully determined up to everything that can affect the results.

Specifying the primary key column (or columns) for the table then becomes an optional optimisation.

As far as our documented behaviour is concerned I think we should say that the results given by an underspecified sort are arbitrary but will be consistent between queries against the same data in the same backend. Making them consistent across query engines is useful for our own testing purposes, but I'm not sure it should form part of our documented behaviour.

**Comment by evansd** [comment]
_Sigh_. The above suggestion is fine in the abstract but it falls down if one of the selected columns is a boolean because:
 1. there's no standard sort order for booleans; and
 2. SQL Server won't let you sort at all on a boolean.

You could work around this by wrapping references to booleans in a case statement which mapped them consistently to ints. But that requires knowing at execution time that an expression _is_ boolean, which means we develop a hard dependency on having a defined schema which we were trying to avoid.

I think we're going to have to allow (but not require) backends to specify a primary key and apply it as a tie-breaker. If no primary key is supplied then we can still run, but the result order is undefined.

**Comment by evansd** [comment]
### Update 2022-10-04

We've now abandoned the idea of building queries where we don't know the full schema in advance. So the strategy mentioned above (sort by all the columns being selected that aren't already being sorted on) ought to work. We also now have the full set of selected columns [to hand](https://github.com/opensafely-core/databuilder/blob/53cceebd19d862acfe329e063ad3531f83cf8a01/databuilder/query_engines/base_sql.py#L425-L441) when building the SQL, which makes the implementation more straightforward.

However, I'm still slightly in two minds as to whether this would be a good thing. There's obviously something nice about being able to say that Data Builder gives deterministic sorts regardless of the vagaries of the database it happens to be run against. But that comes at a cost of complexity, and possibly performance too. And if the only real benefit is to the generative tests then I wonder if it would be better to make sure (somehow) that the tests only generate fully determined sorts.

**Comment by benbc** [comment]
@evansd I'm not sure that sort on all the columns works anyway, does it, if SQL Server doesn't allow sorting on booleans.

**Comment by evansd** [comment]
Ah, but we know they're booleans now (because we always have the schema) so we can turn them into `ints` e.g.
https://github.com/opensafely-core/databuilder/blob/53cceebd19d862acfe329e063ad3531f83cf8a01/tests/acceptance/comparative_booster_study/variables_lib.py#L71-L72

**Comment by benbc** [comment]
I agree that it's probably not sensible to do this just for the benefit of the tests. (But note that, I think, in principle this could apply to the spec tests as well as the generative tests.)

This, I think, is the critical point (from a comment of yours way back at the start of the thread):

> it's definitely caused real world confusion in the past when researchers extracted what should have been the same population twice and got very slightly different results

**Comment by benbc** [comment]
I think we should make a decision based on whether or not that possibility for confusion is sufficiently bad that we should eradicate it.

**Comment by evansd** [comment]
That's quite right, thanks for reminding me. I think that means that deterministic sorts are more than nice-to-have, doesn't it? If we can reasonably achieve them then we probably ought to.

**Comment by benbc** [comment]
And again focusing on user experience rather than developer convenience, the strongest reason _not_ to do it is the performance burden of doing "unnecessary" sorts.

I wonder how clever the SQL engines are -- whether they can ignore the sorts on columns that eventually won't be returned if they don't change the chosen value of the column that is returned.

**Comment by evansd** [comment]
Yes, I think I may have over-egged the performance issues here on reflection.

_We_ can avoid sorting on columns that won't ever be returned, because we already know exactly what columns are going to be selected. (This is the result of the whole `query_model_transforms` fandango where we replace `PickOneRowPerPatient` with `PickOneRowPerPatientWithColumns`.)

So the only sense in which these sorts might be unnecessary is if we've already included a unique column in the sort conditions. But then given that the extra columns can't materially affect the sort order, I expect the performance implications of including them to be negligible. (And if it isn't negligible we should be able to identify and exclude them ourselves as long as we have the unique constraint represented in our schema.)
