### ISSUE TITLE
Placeholder: Support tables without contracts

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/databuilder#526]
(Was [Magic contract](https://app.shortcut.com/ebm-datalab/story/605/magic-contract) in Shortcut.)

**Comment by evansd** [comment]
Depending on what exactly was meant here this is either already done, or never going to be done.

We once floated the idea of having a sort of dynamically generated schema which let you reference any tables and columns you liked and would just assume that the must exist and give them the type `Any`. However this turned out not to be practical and support for it was removed in
 * https://github.com/opensafely-core/databuilder/pull/664

It's also possible that this ticket referred to having an explicitly defined ehrQL schema with no associated Contract object. This has been supported for a long time.
