### ISSUE TITLE
Review Dependabot security alerts

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/databuilder#579]

**Comment by inglesp** [comment]
See here: https://github.com/opensafely-core/databuilder/security/dependabot

**Comment by evansd** [comment]
This is confusing me because I would have expected all dependencies to be kept up to date by dependabot. It's certainly updating [_some_ things](https://github.com/opensafely-core/databuilder/pulls?q=is%3Apr+label%3Adependencies) but clearly not everything.

Is it something to do with this?
https://github.com/opensafely-core/databuilder/blob/08b3895f79d155075d2c295f5d64619da14003ad/requirements.prod.in#L1

More research is needed ...

**Comment by rebkwok** [comment]
It looks like github is picking up the security updates from requirements.dev.txt and requirements.prod.txt, but dependabot uses pyproject.toml to look for version updates
https://github.com/opensafely-core/databuilder/network/dependencies

According to [this page](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow) the default is to check explicitly defined dependencies for updates; possibly if we included 
```
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
```
in the dependabot.yml, it would pick up indirect dependencies (e.g. the numpy is a dependency of pandas, not explicilty stated in the pyproject.toml).

**Comment by rebkwok** [comment]
Although, looking at the list of PRs that dependabot has created, I think it may in fact only be looking at the dev ones.  Pandas was at v1.3.4 and the latest is 1.4.3 (which also pulls in the numpy version that the security update wants)

I thought I found issues that implied that dependabot did deal with pyproject.toml now, but maybe it only supports poetry dependencies?
This issue is still open and has references to updating the pyproject.toml parsing.
https://github.com/dependabot/dependabot-core/issues/3290#issuecomment-996694772
