### ISSUE TITLE
Create contract(s) for SGSS data

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/databuilder#589]
[We've provided Graphnet with contracts for all the tables we expect to use in the CIPHA study](https://github.com/opensafely-core/databuilder/issues/485), except for the Second Generation Surveillance System (SGSS) data.  This is:

> the national laboratory reporting system used in England to capture routine laboratory data on mainly infectious diseases and antimicrobial resistance

[The study we're re-running in Graphnet](https://github.com/opensafely/comparative-booster/blob/main/analysis/study_definition.py) defines five variables based on SGSS data:

```
    ...
    covid_test_0_date=patients.with_test_result_in_sgss(
        pathogen="SARS-CoV-2",
        test_result="any",
        on_or_before="covid_vax_disease_3_date - 1 day",
        returning="date",
        date_format="YYYY-MM-DD",
        find_last_match_in_period=True,
        restrict_to_earliest_specimen_date=False,
    ),
    postest_0_date=patients.with_test_result_in_sgss(
        pathogen="SARS-CoV-2",
        test_result="positive",
        returning="date",
        date_format="YYYY-MM-DD",
        on_or_before="covid_vax_disease_3_date - 1 day",
        find_last_match_in_period=True,
        restrict_to_earliest_specimen_date=False,
    ),
    prior_covid_test_frequency=patients.with_test_result_in_sgss(
        pathogen="SARS-CoV-2",
        test_result="any",
        between=[
            "covid_vax_disease_3_date - 182 days",
            "covid_vax_disease_3_date - 1 day",
        ],  # 182 days = 26 weeks
        returning="number_of_matches_in_period",
        date_format="YYYY-MM-DD",
        restrict_to_earliest_specimen_date=False,
    ),
    covid_test_date=patients.with_test_result_in_sgss(
        pathogen="SARS-CoV-2",
        test_result="any",
        on_or_after="covid_vax_disease_3_date",
        find_first_match_in_period=True,
        restrict_to_earliest_specimen_date=False,
        returning="date",
        date_format="YYYY-MM-DD",
    ),
    postest_date=patients.with_test_result_in_sgss(
        pathogen="SARS-CoV-2",
        test_result="positive",
        returning="date",
        date_format="YYYY-MM-DD",
        on_or_after="covid_vax_disease_3_date",
        find_first_match_in_period=True,
        restrict_to_earliest_specimen_date=False,
    ),
    ...
```

This suggests that we expect a table with the following fields:

* pathogen
* date
* result (one of: "positive", "negative")

However, there are limitations to the SGSS data, [documented here](https://docs.opensafely.org/study-def-variables/#sgss), and the data we get in the TPP backend is actually in two tables (`SGSS_Positives` and `SGSS_Negatives`).  

Whoever picks this up should talk to @sebbacon, who has already done [a lot of thinking around this](https://docs.google.com/document/d/1Gk66X_jNmm2g1ffr3jlfi_XzKlYcxq1Ibc-8DS0NoQE/edit#heading=h.u76qw5q5fl0l), but note that we do not have to implement the fullest version of a contract for the CIPHA study.

To deliver this ticket, we need to:

- [x] put together a contract or contracts
- [x] add to the Contracts tab on [this spreadsheet](https://docs.google.com/spreadsheets/d/1Fu5cfmoUHGC4CY4OdEn-7rchhzjMMy--luAQJMeYlr4/edit#gid=2100914852)
- [x] let Graphnet know (via @benbc) that we've got a contract for them

**Comment by rebkwok** [comment]
For the contract specifically for the CIPHA study, I think the contract table would need:

  | Variable | Description for end users | Notes for implementers | Notes implementers should consider supplying for end users | Type | Validation | Nulls | Rqd | Used in CIPHA?
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
UK/NHSE/CovidSGSS | specimen_date | Date the specimen was taken | In TPP this data comes in 2 tables: SGSS_AllTests_Positive and SGSS_AllTests_Negative |   | Date |   | FALSE | TRUE | yes
  | is_positive | Whether the test result was positive |   |   | Boolean |   | FALSE | TRUE | yes

The study variables only require the All Tests dataset, which is much more straightforward than the Earli'est Specimen Dataset, and we don't need to implement that yet.  I've used variable names that match the acceptance test @dave referenced above, rather than the names in the current databuilder contract (which I think are old).  

Agree with Dave that the `pathogen` variable is redundant; in cohort-extractor there's an assertion in the code so if a user ever provides anything other than "SARS-Cov-2", it will raise an error.

Also, I added a note about the data coming in 2 tables in TPP, but I don't know that we should expect it to be the same in Graphnet.  At least in the previous implementation, they did the UNION table prior to the backend implementation.  (This isn't part of the contract per se though, I think.)

**Comment by sebbacon** [comment]
The reason I suggested `specimen_taken_date` rather than `specimen_date` in the contracts doc is that in general pathology data specimens go through all sorts of stages (taken, sent, analysed, returned). Making the variable name self-documenting in this regard seems useful?

**Comment by rebkwok** [comment]
Makes sense, yes.  So to confirm, the entry for the SGSS contract will be:

  | Variable | Description for end users | Notes for implementers | Notes implementers should consider supplying for end users | Type | Validation | Nulls | Rqd | Used in CIPHA?
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
UK/NHSE/CovidSGSS | specimen_taken_date | Date the specimen was taken | In TPP this data comes in 2 tables: SGSS_AllTests_Positive and SGSS_AllTests_Negative |   | Date |   | FALSE | TRUE | yes
  | is_positive | Whether the test result was positive |   |   | Boolean |   | FALSE | TRUE | yes

**Comment by rebkwok** [comment]
@benbc I have added to the contract spreadsheet. Please can you inform Graphnet.

**Comment by benbc** [comment]
@rebkwok Done, thanks. I'll mark this issue as done.
