### ISSUE TITLE
Reviewing readability of ehrQL from researcher perspective

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/databuilder#622]

**Comment by CarolineMorton** [comment]
🚧🚧 **_Draft_ - DO NOT READ YET** 🚧🚧

**Focus**
This ticket is all about the user perspective of using ehrQL. We want researchers to be able to use ehrQL intuitively and to feel reassured that the code is doing what they think it is doing. 

**Users**

- Existing users of cohortextractor and study definitions
- New users 

**Composibility**
- `take()` ==> refers to take the value if it is not null, _i think_. If this is the case, could this be changed to `take_value_if_not_null()`. Just to increase the readability. 
- `case()` ==> categorisation into groups, for example if bmi<25, then x. I think we could clarify this perhaps into categorise (if that in itself is not a loaded term). We should stay away from group or groupby due to pandas and R terms being similar/same. 
- in built variables such as `dataset.msoa` or `dataset.imd` are easy to read. 
- `last_for_patient()` ==> If this is just for dates and returning of those dates, could we use `last_date_for_patient`. If it is possible to also return a value (i.e. latest haemoglobin), then I think fine to keep as is. 
- Some confusion might occur between `last_for_patient` and `last_prior_event`

**Other thoughts**
- It would be good to have VS code or another IDE be able to give useful information to users when they are writing code. I think we can do this via doc strings.
