### ISSUE TITLE
It would be friendly of Data Builder to list available backends when you run a command without providing one

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/databuilder#646]
For example, currently running `dump-dataset-sql` without specifying a backend gives this:

```
❯ python -m databuilder dump-dataset-sql --dataset-definition tests/acceptance/comparative_booster_study/dataset_definition.py 
usage: databuilder dump-dataset-sql [-h] --dataset-definition DATASET_DEFINITION [--output OUTPUT]
                                    backend
databuilder dump-dataset-sql: error: the following arguments are required: backend
error: Recipe `exec` failed on line 137 with exit code 2
```

Even as someone familiar with the codebase, I'm not sure if I should be giving the class name, the module name or some special registered name to identify the codebase.

**Comment by inglesp** [comment]
Originally added as a draft by @benbc.

**Comment by evansd** [comment]
I think this is obviated by #608.

There's a separate question about making backends and query engines easier to specify by not always requiring the full dotted path (e.g. by defining aliases like `tpp` -> `databuilder.backends.tpp.TPPBackend`).

**Comment by benbc** [comment]
> I think this is obviated by https://github.com/opensafely-core/databuilder/pull/608.

I'm not sure about that. How does the user determine what the valid values of `--backend` and `--query-engine` are?

**Comment by evansd** [comment]
Yes, there is something to be done here — although literally as written the ticket doesn't apply anymore because databuilder no longer throws an error when you don't provide a backend.

But I think it would be good to provide short aliases for the built-in backends/query engines, and enumerate these to the user, while also making clear that any importable dotted path can be used as well.
