### ISSUE TITLE
Latest tag is `vnull` and shouldn't be

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/databuilder#651]
There was a recent change to how we retrieve the previous tag: 90e0aa7c9ecc333fec84badab9fc63b2eb336c0c.

Somehow this has ended up as `null`. This means we have:

* a `vnull` [tag](https://github.com/opensafely-core/databuilder/releases/tag/vnull)
* a `vnull` [Docker image](https://github.com/opensafely-core/base-docker/pkgs/container/databuilder/29274340?tag=vnull) 

It's possible that there was a temporary outage to GitHub's API, perhaps.

If that was the cause, and there's no way to make this more robust, then we should probably fail at that step if we can't resolve a valid tag.

**Comment by StevenMaude** [comment]
It might be that there's only a release if `public_docs.json` updates, perhaps?

**Comment by rebkwok** [comment]
The issue actually seems to be in the tagging action:
https://github.com/opensafely-core/databuilder/runs/7469012936?check_suite_focus=true#step:3:113

It's setting the `previous_tag` to the last tag, which is a `docs-metadata-xxx` one, and as a result it doesn't parse a previous version, and gets `null` instead.  I had thought that the `tag_prefix: v` [setting](https://github.com/opensafely-core/databuilder/runs/7469012936?check_suite_focus=true#step:3:6) meant that it would parse only tags starting withthe prefix, but apparently it just means it'll label them with it.  

There is an [issue](https://github.com/mathieudutour/github-tag-action/issues/71) in the action repo about confusion with other tags which seems related, although not identical to ours.  (Issue was opened in March 2021 and hasn't had any response from the repo owner though.)

The docs tag and release isn't essential now.  Previously we were using it to upload the public.json file as a release asset which the docs repo workflow would have access to.  However, now we're pulling the docs repo in the databuilder workflow in order to check if the docs have been updated and a new docs PR is needed.  We could manually tag the latest commit that should be tagged with a v0.x.x tag, and get rid of the release part of the docs workflow.
