### ISSUE TITLE
Test database setup/teardown code needs refactoring

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#656]
This issue is a good opportunity to learn more about pytest and our database fixtures.

# Background

At present, our test setup/teardown approach is a bit backwards: rather than dropping any tables we've created during a test run at the end of the test, we conditionally drop any tables we're _about_ to create at the start of the test run.

This mostly works fine, but it has some nasty corner cases. For instance if two tests use a table with the same name, but test A adds foreign keys to other tables which test B doesn't use, then test B won't be able to drop the table created by test A.

As an example, if you run this pair of tests:
```
pytest \
 tests/acceptance/comparative_booster_study/test_dataset_definition.py \
 tests/integration/backends/test_tpp.py
```

With this workaround removed:
https://github.com/opensafely-core/databuilder/blob/fd93064f98ed27a87162b45744ff840111f45dd4/tests/acceptance/comparative_booster_study/test_dataset_definition.py#L31-L33

Then you get this error:
```
Could not drop object 'APCS' because it is referenced by a FOREIGN KEY constraint.DB-Lib error message 20018
```

In this particular case the issue is easy enough to work around. But we'd benefit from a more standard approach here.

# Approach

Modify the [`engine`](https://github.com/opensafely-core/databuilder/blob/5e2352dfefcd4bf0b43dee2b8179dceb2d6592af/tests/conftest.py#L116) fixture, to make it a [yield fixture](https://docs.pytest.org/en/6.2.x/fixture.html#yield-fixtures-recommended). After yielding the engine the fixture should call a new method `clean_up()` on it. `clean_up()` should delegate to a `clean_up()` method on the database.

The database's `clean_up()` method needs implementing in two places. On [`InMemoryDatabase`](https://github.com/opensafely-core/databuilder/blob/6073bd88e93512f2dfc03c3d3ac63bc2f6ebd0f6/databuilder/query_engines/in_memory_database.py#L14) it is a no-op (because the in-memory database does not have any persistent resources to clean up). On [`DbDetails`](https://github.com/opensafely-core/databuilder/blob/6073bd88e93512f2dfc03c3d3ac63bc2f6ebd0f6/tests/lib/databases.py#L24) it needs to drop all the created tables by calling `metadata.drop_all(engine)`; this should be moved from `setup()` where it's currently called before the schema is created. (Note that this will require changing `DbDetails` to record the `metadata` during `setup()`.)

After this change you should remove the [workaround](https://github.com/opensafely-core/databuilder/blob/fd93064f98ed27a87162b45744ff840111f45dd4/tests/acceptance/comparative_booster_study/test_dataset_definition.py#L31-L33) mentioned above.

**Comment by inglesp** [comment]
This is a plumbing problem.  Unfortunately moving `metadata.drop_all(engine)` from `DbDetails.setup` to `DbDetails.teardown` isn't sufficient, because in many cases `DbDetails.setup` is not called from a function-scoped fixture (such as `engine`).

See for instance [test_tpp.py](https://github.com/opensafely-core/databuilder/blob/84245d5b022cfdbbbd1e359fe88e50c850f50306/tests/integration/backends/test_tpp.py#L61-L65) or [test_embedded_study.py](https://github.com/opensafely-core/databuilder/blob/main/tests/acceptance/test_embedded_study.py#L15-L33).

This means that unless we sprinkle the code with lots of `try`/`finaly`s, we can't guarantee that the database will be torn down, risking us leaving with a database in an unknown state.

One solution might be to turn `DbDetails.setup` into a context manager, allowing us to safely do:

```
with mssql_database.setup(*input_data):
    with mssql_database.engine().connect() as connection:
        results = connection.execute(select_all_query)
        return [dict(row) for row in results]
````

or

```
with mssql_database.setup(
    patient(dob=datetime(1943, 5, 5)),
    patient(dob=datetime(1999, 5, 5)),
):
    study.generate(
        mssql_database, "databuilder.backends.tpp.TPPBackend", extension=extension
    )
    results = study.results()
```

But without trying this, I'm not sure whether this will work everywhere, and in particular, I'm not sure off the top of my head how to do this with `QueryEngineFixture`.
