### ISSUE TITLE
Convert ONS CIS validation study to ehrQL

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/databuilder#747]
We would like to convert this [study definition](https://github.com/opensafely/CIS-pop-validation/blob/main/analysis/study_definition.py) to ehrQL.  This ticket does not cover working out how to support measures in databuilder.

This will improve our understanding of how ehrQL can be used in the real world.  We should work closely with @wjchulme to ensure (a) that the new code matches the behaviour of the old code, and (b) that the new code is comprehensible to researchers.

We should aim validate the new code by running the dataset-report action over the outputs of both the old and the new code, and check for parity.  A separate ticket covers the work required for dataset-report to support this.

**Comment by wjchulme** [comment]
cc @LindaNab who will also be working on the actual study

**Comment by milanwiedemann** [comment]
wehoo, the job completed successfully. the main chunk of this ticket is addressed in https://github.com/opensafely/cis-pop-validation-ehrql/pull/1 with lots of feedback from @StevenMaude. do we still think we need a closer look from @evansd at this stage or discuss the comments from Steve together before we consider this ticket "done"? 

Also, I have started working on the dataset report mentioned at the end of this ticket https://github.com/opensafely/cis-pop-validation-ehrql/pull/4 but it would be good to clarify some details how to do best do this. especially because there is a chance that comparing the results between cohort-extractor vs. ehrQL may result in further work related to this ticket (translation cohort-extractor to ehrQL)

**Comment by milanwiedemann** [comment]
I tidied the project up for now but we may decide to continue at a later stage. for example:

- check differences in more variables that we currently don't explore (e.g., clinical events)
- integrate (and improve) the pytests for dummy data into the pipeline when running project locally (low priority, we should wait until we have a better idea how we do testing of research studies)
- explore options for more formal testing of comparability between cohort-extractor functions and (near) identical ehrQL implementations (not part of this project but a possible continuation we might want to explore)

**Comment by StevenMaude** [comment]
Because this issue and the associated pull request both appeared in my notifications, I'll note here that there's a slight mismatch between:

* the state of "Done" on the project board for this issue
* this issue being left open and the [suggestion](https://github.com/opensafely-core/databuilder/issues/747#issuecomment-1363174043) that there's more to do in future

I'm not *quite* sure what the correct resolution is here though.
