### ISSUE TITLE
`databuilder --version` output duplicates the version number

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#801]
The version reported by `databuilder` run via the Docker image is weirdly duplicated.

```
> docker run --rm ghcr.io/opensafely-core/databuilder:v0 --version
databuilder v0.v0.65.v0.65.2
```

Investigate and fix.

**Comment by iaindillingham** [comment]
Fun! Yes, I'll 👀

**Comment by StevenMaude** [comment]
I think this is just an oversight in the workflow line that sets the version:

https://github.com/opensafely-core/databuilder/blob/c52ea8fc1026390fef77be44256a24da6182884d/.github/workflows/build-and-deploy.yml#L94-L102

The `PATCH` version is the full version number, `vX.Y.Z`, *not* just the `Z`. And the `MAJOR` and `MINOR` simply truncate the full version to `vX` and `vX.Y` respectively.

That's consistent with `MAJOR.MINOR.PATCH` being `v0.v0.65.v0.65.2`

So I think:

`echo "$PATCH" > databuilder/VERSION` should fix this.

Testing that fix is more trial and error since it's in GitHub Actions, and it requires publishing an image.

**Comment by StevenMaude** [comment]
Checked this after the image build because it was easier then to try and contrive to fork the repository, and then build and publish an image elsewhere.

It works.

old output:

```
$ docker run ghcr.io/opensafely-core/databuilder:v0.69.0 --version
databuilder v0.v0.69.v0.69.0
```

new output:

```
$ docker run ghcr.io/opensafely-core/databuilder:v0.69.3 --version
databuilder v0.69.3
```
