### ISSUE TITLE
Try out moving Data Builder docs into Data Builder repository

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/databuilder#808]
See [this discussion thread](https://bennettoxford.slack.com/archives/C03FB777L1M/p1659345849579569).

Not sure what form this might take.

Current examples of problems:

* https://github.com/opensafely/documentation/issues/886#issuecomment-1204164458 — since completely resolved, FWIW.
* The tutorial examples are in the documentation repository; this means a user has to download the examples from there. This is not terrible, but is a little eccentric.

**Comment by StevenMaude** [comment]
# Current thinking

@rebkwok and I discussed this today and decided that it's at least worth trying out, as there are potentially a number of benefits — see below — from doing so.

We noted that a lot, or even all, of the existing Data Builder documentation is self-contained, as highlighted by the URL restructure in opensafely/documentation#1064.

We also put the dependent docs-based "databuilder-1" issues on hold: #858 and opensafely/documentation#898 until this is evaluated.

:bulb: If this move is successful, we could consider this kind of modularisation of the documentation for other OpenSAFELY components, for example, the CLI and cohort-extractor. (This is not in scope here.)

# Advantages

* Keeps the documentation close to where the code is, meaning changes to both are in a single repository.
* Allows developers to preview documentation changes without having to clone the documentation repository and update requirements there.
* Prevents multiple repeated PRs in different repositories in the case where slight fixes are needed; for instance, because the documentation repository fails to build with a new docstring or similar.
* Should allow syncing up of documentation changes to new releases of Data Builder, to avoid either accidental deploy of [documentation before features](https://github.com/opensafely/documentation/pull/1078) or vice versa
* Should remove the `databuilder` directory from the documentation repository; this solely exists to provide and run dataset definition examples used in the tutorial
* Would allow the databuilder-mkdocs-plugin to be subsumed into the `databuilder` repository, or maybe even dropped entirely.
* Makes it easier for the documentation to "know" which version of Data Builder and sync content and run commands to the actual version of Data Builder. 
* May offer an easier way for users to install the dataset definition examples, perhaps by bundling them within Data Builder, or providing a helper command to download them, instead of a manual .zip download.
* Potentially makes versioning of the Data Builder documentation easier, and able to tie this into a current release.
* Provides a demarcation of documentation ownership.

# Disadvantages

* Easier for a less unified written voice to slip into the documentation, because there is now more than one entry point for documentation prose. This is especially so if we take the idea to the limit of breaking out documentation for more components. Implementing more automated style checks could help here.
  However, a non-unified voice is probably already the case with docstrings and content derived from docstrings and other code — for example, spec tests — anyway. We don't enforce any particular written style anywhere.
* Making quick fixes to the Data Builder documentation and getting them deployed requires two separate PRs. The PR to the documentation repository may well be automated.
* Perhaps trying to construct correct relative links is trickier when working in a subhierarchy of the documentation? The link checker can help here.

# Considerations

* Ideally not disrupting the existing documentation; either working on a branch, or creating a parallel set of documentation, either via separate deployment or separate URL hierarchy, using this new approach
* …while ideally not having large, long-running PRs sat, which might require gnarly rebasing in future to keep sync with any changes to the documentation
* Confirm that there are no other substantial references to Data Builder outside of the subhierarchy in opensafely/documentation#1064
* How do relative links and include files work across the boundary?
* How well maintained is the plugin we intend to use?
* The databuilder repository should duplicate the link checking in the documentation. If we add any other style or content checks in future, these also need to be replicated here. It might be that those checks should be carried out by a shared action stored in another repository, instead of copy-pasting code. It would be fine to copy-paste the existing small amount of workflow code, for now.
* How do we evaluate success?
  * Perhaps by noting the main editor and developer tasks for the documentation, and comparing both approaches. We could quantify this by number of steps for a task, if this is unclear subjectively and we want a rough, qualitative guide.

**Comment by StevenMaude** [comment]
# Tasks

These might be detailed in individual issues if sufficiently complex.

- [ ] Merge opensafely/documentation#1064
- [ ] Attempt to get the documentation repository pulling some content (doesn't matter what specifically) from a working-in-principle repository using the [mkdocs-multirepo-plugin](https://github.com/jdoiro3/mkdocs-multirepo-plugin) that Becky found
- [ ] …

**Comment by rebkwok** [comment]
As a first exploration of getting the docs repo pulling in databuilder content: https://github.com/opensafely/documentation/pull/1090

This pulls in some minimal docs files from the databuilder `docs-spike`, into a "Data Builder" section under "Using OpenSAFELY".   Checkout the `databuilder-docs-spike` branch and run `jun run` as normal, and it should pull in the databuilder repo's docs into the main docs navigation (it might need a git upgrade, see below). 

It's not working in the deploy preview yet, which I'm trying to figure out.

Some thoughts:
- setting this up - from the main docs repo perspectve - was easy.  It required minimal config and pretty much just worked
- it is dependent on some newer git features; on ubuntu 20.04 I had to download the git ppa and upgrade git to a newer version than the standard one that `apt install` installs
- It requires a nav entry; we could probably write something custom to hide it based on a flag in `mkdocs.yml`, but we can't have the databuilder docs only findable by url as they are now
- I haven't tried out includes (i.e. including bits of the main docs in the db docs) but I think they might work for the main docs at least - but that might be just as confusing as having the docs split between repos.  If we do this, we might need to consider imported docs entirely self-contained in terms of content, so any includes live with databuilder.
- the plugin has a beta feature for running the docs within the imported repo (databuilder in this case); the intention is that it would pull in the theming from the parent repo so you see just the databuilder docs, but with the main docs theming.
- This doesn't work so well; partly I think it's because our main docs are complex.  The `macro` plugin doesn't play nicely, particularly.  I got it to work by making it a copy of the docs `mkdocs.yml` that omits all the plugins, but that's not ideal.  If we don't include this feature, and all databuilder docs are self-contained (i.e. no trying to `include` things that are in the main docs repo), we should still be able to run the databuilder docs alone

**Comment by rebkwok** [comment]
Deploy preview is now working, it just needed an env variable

**Comment by StevenMaude** [comment]
# Known issues (WIP)

* Handling redirects is done at the "parent" documentation repository level.
  * However, this should be an uncommon task.
* …

**Comment by StevenMaude** [comment]
This is pretty much done now, so planning to close shortly. I'll update the above comments where appropriate first, before closing.

#980 should be revisited, but this is more about being tidy, than implementing some missing functionality.
