### ISSUE TITLE
Add acceptance tests for in-development studies

### ISSUE THREAD

**Issue by benbc** [opensafely-core/databuilder#875]
For each of our [in-development studies](https://docs.google.com/spreadsheets/d/1-lw0qZSRdZwPY2HrQh_wDkifvJKvtqR6WKie_WLQNJI/edit#gid=0), add a test case in [test_external_studies.py](https://github.com/opensafely-core/databuilder/blob/d03f997aef3769b916aa3bfd33e9b306c9e0a39d/tests/acceptance/test_external_studies.py) to let us know if we break backwards-compatibility with the studies that have been written so far.

**Comment by rebkwok** [comment]
@benbc 2 questions:
1) Should we add acceptance tests for all of the external studies, even if they're not done yet?
2) For the [openprompt long covid vaccine study](https://github.com/opensafely/openprompt-vaccine-long-covid), is analysis/dataset_definition.py going to be used?  It's not in the project.yaml, and it's failing the external study test because it uses an undefined `study_end_date` variable [here](https://github.com/opensafely/openprompt-vaccine-long-covid/blob/main/analysis/dataset_definition.py#L44).  I'm not sure if this is an error, or the study is waiting on paramterisable dataset defs.

**Comment by rebkwok** [comment]
If I include the studies that aren't complete yet, a couple will need to use branches other than main, and will need to be updated later:
- bias study: currently using `evansd/ehrql-translation` branch
- Nuffield medication validation study: currently using `validation` branch

**Comment by evansd** [comment]
Can I add another question here? Some of the in development studies are private. But vendoring them into Data Builder effectively makes them public. Do we know whether this acceptable?

**Comment by rebkwok** [comment]
Hmm, that's a good point. I had to add auth headers so that the tests could run on private repos, but maybe they just shouldn't be included until they're public

**Comment by benbc** [comment]
@rebkwok  I can get an answer to the question about the OpenPROMPT study, but I'd rather you, @inglesp and @evansd took whatever route you think best for the rest of this.

**Comment by benbc** [comment]
I'm pretty sure that `analysis/dataset_definition.py` in that study is left around from some earlier development. You can ignore it.

**Comment by benbc** [comment]
I'm pretty sure that `analysis/dataset_definition.py` in that study is left around from some earlier development. You can ignore it.

**Comment by rebkwok** [comment]
See https://bennettoxford.slack.com/archives/C03FB777L1M/p1677835053960809
