### ISSUE TITLE
Dummy data test test_get_random_value_on_first_of_month failure

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/databuilder#961]
Seen once only as far as I'm aware, and can't reproduce locally so far

Seen on:
https://github.com/opensafely-core/databuilder/actions/runs/3967909678/jobs/6800420732#step:4:457

```
  =================================== FAILURES ===================================
  ___________________ test_get_random_value_on_first_of_month ____________________
  Traceback (most recent call last):
    File "/home/runner/work/databuilder/databuilder/tests/unit/dummy_data/test_generator.py", line 125, in test_get_random_value_on_first_of_month
      assert len(set(values)) > 1, "dates are all identical"
  AssertionError: dates are all identical
  assert 1 > 1
   +  where 1 = len({datetime.date(2023, 1, 1)})
   +    where {datetime.date(2023, 1, 1)} = set([datetime.date(2023, 1, 1), datetime.date(2023, 1, 1), datetime.date(2023, 1, 1), datetime.date(2023, 1, 1), datetime.date(2023, 1, 1), datetime.date(2023, 1, 1), ...])
```

**Comment by evansd** [comment]
I notice that there was also an error concerning the number of rejected examples:
```
 _____ ERROR at teardown of test_type_matches_only_with_consistent_typevar ______
  Traceback (most recent call last):
    File "/home/runner/work/databuilder/databuilder/tests/generative/recording.py", line 63, in recorder
      check_not_too_many_ignored_errors(recorder_)
    File "/home/runner/work/databuilder/databuilder/tests/generative/recording.py", line 77, in check_not_too_many_ignored_errors
      assert recorder.num_ignored_errors / recorder.num_results <= 0.01
  AssertionError
```

I re-ran the workflow in CI and the dummy data test failure disappeared but the above error still occurred.

I attach the original logs (from before I re-ran the workflow) in case that's useful for future debugging:
[consolidated-logs.txt](https://github.com/opensafely-core/databuilder/files/10482462/job-logs.txt)
[logs_4187.zip](https://github.com/opensafely-core/databuilder/files/10482458/logs_4187.zip)

**Comment by rebkwok** [comment]
The rejected errors is a different issue, that I've fixed in the [PR](https://github.com/opensafely-core/databuilder/pull/959) where this test failure happened.  I don't think it's likely to be related - the rejected examples check only relates to the generative tests.  I haven't been able to reproduce the dummy data test failure anywhere else, other than this one CI run.

**Comment by inglesp** [comment]
The tests are non-deterministic, because [they use today's date](https://github.com/opensafely-core/databuilder/blob/f0a3009aac8ecfa17ceb1d3a28df9256ea748413/databuilder/dummy_data/generator.py#L111-L114).

Run today, 8% of dates generated in this test are for the same date (March 1st).  This test generates 10 dates, and the chance of all being the same are >1%.  Assuming that this implies there's a 1% chance of this happening on any given day (which is not given, but I can't be bothered to work out the real probability.

Either:

* we live with this;
* we remove the assertion that the dates are not identical;
* we generate 100 random dates, which makes the chance of a duplicate around the same as winning the lottery 17 times on the trot.

I think we should do the latter and I'll make a PR now.
